- name: Ensure nginx deployed
  hosts: webservers
  become: true
  
  tasks:
    - name: Ensure nginx installed
      apt:
        name: nginx
        state: latest
        update_cache: true

    - name: Ensure index exists with content
      copy:
        src: ./index.html
        dest: /var/www/html/index.nginx-debian.html
        owner: root
        group: root
        mode: '0666'

    - name: Ensure nginx service is enabled
      service:
        name: nginx
        state: started
        enabled: true


